### PR TITLE
editorial changes to README

### PR DESCRIPTION
**Pull request by eckelcu**

### CODE REVIEW

**Comment by FragmentedPacket** [comment]
Sorry for getting back to you months later. Life has been super busy.

I made some changes and merged it into the `master` branch. Is this now acceptable?

**Comment by eckelcu** [comment]
The changes look good, but one question still remains in my mind. The title makes it sound like this repo pertains to IOS XE devices in general,
“Cisco IOS-XE Guestshell ZTP Script”

But the requirement limit usage to the Catalyst 9000 series,
“Requirements

  1.  Catalyst 9000 series switch”

As I understand it, guestshell is part of Cisco IOX, and IOX is supported on NX OS, IOS XE, and IOS XR devices. If your code is for using it specifically for Catalyst 9000 series switches only, perhaps a better title would be the following?
“Cisco IOX guestshell ZTP script for Catalyst 9000 series switches”

Cheers,
Charles

**Comment by FragmentedPacket** [comment]
I changed it to be more specific. I was hoping it would expand to Catalyst 38XX, but I no longer work in an environment where I have this physical hardware to expand the script on at this moment.

**Comment by eckelcu** [comment]
Thanks for updating. Your repo has been approved and published in Code Exchange. https://developer.cisco.com/codeexchange/github/repo/FragmentedPacket/cisco-ztp

**Pull request closed without merging**
